name: redlines

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) 根目录必须干净（防止再出现 gemini_* 残留）
      - name: Root must be clean
        shell: bash
        run: |
          set -euo pipefail
          if ls -1 | egrep -q '^(gemini_cache\.sqlite|gemini_integration\.py)$'; then
            echo "❌ Root polluted by Gemini files"
            ls -la | egrep 'gemini_cache\.sqlite|gemini_integration\.py' || true
            exit 1
          fi
          echo "✅ Root clean"

      # 2) 禁止主回路导入外部 LLM（Sidecar/integrations 与 data 均豁免）
      - name: Ban external LLM imports in main loop
        shell: bash
        run: |
          set -euo pipefail
          if grep -RInE 'google\.generativeai|openai|anthropic' \
               --include='*.py' \
               --exclude-dir=integrations --exclude-dir=.git --exclude-dir=data \
               src/ tools/ train/ 2>/dev/null; then
            echo "❌ Found forbidden imports in main loop (src/tools/train)"
            exit 1
          fi
          echo "✅ No forbidden imports in main loop"

      # 3) （可复算）质量脚本检查 —— 让它可跑且不易因依赖缺失挂掉
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Recount metrics (repro check)
        shell: bash
        run: |
          set -euo pipefail
          if [ -f tools/quality/recount_metrics.py ]; then
            # 若仓库没有 requirements.txt，就别失败
            if [ -f requirements.txt ]; then
              python -m pip install --upgrade pip
              pip install -r requirements.txt || true
            fi
            python tools/quality/recount_metrics.py --check
          else
            echo "ℹ️ recount_metrics.py not found; skipping"
          fi
