name: redlines
on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Root must be clean
        shell: bash
        run: |
          set -euo pipefail
          if ls -1 | egrep -q '^(gemini_cache\.sqlite|gemini_integration\.py)$'; then
            echo "❌ Root polluted by Gemini files"
            exit 1
          fi
          echo "✅ Root clean"

      - name: Ban external LLM imports in main loop
        shell: bash
        run: |
          set -euo pipefail
          if grep -RInE '^[[:space:]]*(from|import)[[:space:]]+(google\.generativeai|openai|anthropic)\b' \
               --include='*.py' \
               --exclude-dir=integrations --exclude-dir=.git --exclude-dir=data \
               src/ tools/ train/ 2>/dev/null; then
            echo "❌ Found forbidden *imports* in main loop (src/tools/train)"
            exit 1
          fi
          echo "✅ No forbidden imports in main loop"

      - name: Sanity echo
        run: echo "✅ workflow parsed & ran"
